// Per-reciter style profiles — statistical summaries (NOT a trained model) of
// how a specific reciter typically paces Madd elongation, nasal holds, and
// pauses, and how volatile their pitch contour is. Built for reciters with
// no QUA ground-truth timing (see quaReferenceData.js) so Tajweed checks can
// eventually compare a user against THAT reciter's own typical delivery
// instead of one generic baseline for every reciter (Phase 2 — not wired in
// yet; this file is data only).
//
// Generated by tools/qdat-eval/build-reciter-profile.mjs +
// compile-reciter-profile.mjs — do not hand-edit; re-run the scripts to
// update or add a reciter.
//
// Scope, deliberately narrow: every stat here is TIMING/RHYTHM/PITCH-
// CONTOUR-SHAPE only. maddElongationMultiplier and nasalHoldMultiplier are
// dimensionless duration ratios; pauseRatePerActiveMinute/avgPauseDurationSec
// are pure timing between words; pitchContourVolatilitySemitones is a
// standard deviation (shift-invariant, so it can't reflect pitch REGISTER)
// computed with no spectral/formant analysis (so it can't reflect voice
// TIMBRE either). Qalqalah bounce-dB is deliberately NOT profiled here — see
// build-reciter-profile.mjs's header comment for why.
export const RECITER_STYLE_PROFILES = {
  "Alafasy_128kbps": {
    "reciterFolder": "Alafasy_128kbps",
    "generatedAt": "2026-07-26",
    "model": "onnx-community/whisper-base_timestamped",
    "sampleAyahs": 285,
    "sampleErrors": 0,
    "maddElongationMultiplier": 1.059,
    "maddOccurrences": 1162,
    "nasalHoldMultiplier": 2.599,
    "nasalOccurrences": 574,
    "pauseRatePerActiveMinute": 0.257,
    "avgPauseDurationSec": 0.361,
    "pauseOccurrences": 18,
    "pitchContourVolatilitySemitones": 2.694,
    "pitchSampleAyahs": 285
  }
};
